### ISSUE TITLE
except IOError, Argument

### ISSUE THREAD

**Issue by runo280** [irLinja/PhotoSort#1]
Installed needed packages via virtualenv and tried to run the script but got error:
```
./photosort.py -h
```
Output:
```
File "./photosort.py", line 33
    except IOError, Argument:
                  ^
SyntaxError: invalid syntax
```

**Comment by irLinja** [comment]
Hey,
Thanks for feedback.
Would you please provide more details like python version you are trying to run script with?

**Comment by runo280** [comment]
I'm running it under `Ubuntu 16.04` and `Python 3.5.2` and `Virtualenv 15.1.0`.
Things I did:
```
virtualenv me
source me/bin/activate
pip install exifread jdatetime termcolor
./photosort.py -h
```
I should written them on first message, execute me :grinning: 
Currently I'm trying to write it's Java version :innocent: but I hope this script fixed.
انگلیسیم تموم شد دیگه 🙈

**Comment by irLinja** [comment]
It's not compatible with python 3.
Please use python 2 with/without virtualenv and let me know the result.
also you can try to port it to python 3 using [`2to3`](https://docs.python.org/3.0/library/2to3.html) at your own risk.
If you decide porting it, I would appreciate if you post the results back and any PRs are welcome.

**Comment by runo280** [comment]
Thanks, changed python version to 2.7 and script had run successfully, also I'm still using virtualenv 😀.
About porting, I haven’t enough knowledge in python, may be in future.
